#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
	use dns
}

start() {
	ebegin "Starting bareos file daemon"
	start-stop-daemon --start --quiet --exec /usr/sbin/bareos-fd \
		-- ${FD_OPTIONS}
	eend $?
}

stop() {
	ebegin "Stopping bareos file daemon"
	start-stop-daemon --stop --quiet --pidfile /run/bareos-fd.*.pid
	eend $?
}
