#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
	use dns bareos-fd bareos-sd
}

start() {
	ebegin "Starting bareos director"
	start-stop-daemon --start --quiet --exec /usr/sbin/bareos-dir \
		-- ${DIR_OPTIONS}
	eend $?
}

stop() {
	ebegin "Stopping bareos director"
	start-stop-daemon --stop --quiet --pidfile /run/bareos-dir.*.pid
	eend $?
}
