#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
	use dns
}

start() {
	ebegin "Starting bareos storage daemon"
	start-stop-daemon --start --quiet --exec /usr/sbin/bareos-sd \
		-- ${SD_OPTIONS}
	eend $?
}

stop() {
	ebegin "Stopping bareos storage daemon"
	start-stop-daemon --stop --quiet --pidfile /var/run/bareos-sd.*.pid 
	eend $?
}
